### ISSUE TITLE
Report doesn't show the relevant pod

### ISSUE THREAD

**Issue by quocvd1511** [turbot/steampipe-mod-kubernetes-compliance#21]
**Describe the bug**
Report doesn't show the relevant pod so i cannot know which pod is alarm or ok.
<img width="884" alt="Screen Shot 2022-10-30 at 3 09 58 PM" src="https://user-images.githubusercontent.com/90229548/198868958-92cecb67-c6f7-430d-a6f2-1388c971830c.png">

<img width="884" alt="Screen Shot 2022-10-30 at 3 11 43 PM" src="https://user-images.githubusercontent.com/90229548/198868969-806aa1a3-75a5-4249-8bef-4f6e073f36a5.png">

**Steampipe version (`steampipe -v`)**
steampipe version 0.16.1

**Plugin version (`steampipe plugin list`)**

+-------------------------------------------------------------------+
|                                                                   |
| A new version of Steampipe is available! 0.16.1 → 0.16.4          |
| You can update by downloading from https://steampipe.io/downloads |
|                                                                   |
|                                                                   |
| Updated versions of the following plugins are available:          |
|                                                                   |
|   turbot/gcp @ latest               0.26.0 → 0.28.0               |
|                                                                   |
| You can update by running steampipe plugin update --all           |
|                                                                   |
+-------------------------------------------------------------------+

+---------------------------------------------------+---------+-------------+
| Name                                              | Version | Connections |
+---------------------------------------------------+---------+-------------+
| hub.steampipe.io/plugins/turbot/gcp@latest        | 0.26.0  | gcp         |
| hub.steampipe.io/plugins/turbot/kubernetes@latest | 0.12.0  | kubernetes  |
+---------------------------------------------------+---------+-------------+

**To reproduce**
steampipe check kubernetes_compliance.benchmark.cis_kube_v120 --export html

**Expected behavior**
The report need to show the name of resource or name of the pod.

**Comment by bigdatasourav** [comment]
@quocvd1511 thanks for raising this issue; we are looking into it.

**Comment by misraved** [comment]
Fixed in https://github.com/turbot/steampipe-mod-kubernetes-compliance/pull/23
