### ISSUE TITLE
Controls should reference their query using `query =` rather than `sql =`

### ISSUE THREAD

**Issue by e-gineer** [turbot/steampipe-mod-kubernetes-compliance#22]
It's simpler in code and readability to reference queries using the `query =` attribute rather than the `sql =` attribute.

This occurs throughout the mod, but as a specific example:

https://github.com/turbot/steampipe-mod-kubernetes-compliance/blob/c535281192b9f0dc92eabe7d360b39e95e9c84b6/cis_kube_v120/cis_kube_v120_v100.sp#L188-L200

Could be changed from:
```
  sql           = query.pod_security_policy_container_privilege_escalation_disabled.sql
```

to:
```
  query         = query.pod_security_policy_container_privilege_escalation_disabled
```

**Comment by khushboo9024** [comment]
Completed as per https://github.com/turbot/steampipe-mod-kubernetes-compliance/pull/28
