### ISSUE TITLE
The named query for the control breaks in hub site

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-mod-kubernetes-compliance#36]
**Describe the bug**

Some of the controls are not rendering, 
https://hub.steampipe.io/mods/turbot/kubernetes_compliance/queries/cronjob_default_seccomp_profile_enabled 

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by rajlearner17** [comment]
https://github.com/turbot/steampipe/issues/3405

**Comment by misraved** [comment]
The issue has now been fixed 👍.
