### ISSUE TITLE
Add CIS Kubernetes Foundations Benchmark v1.7.1- (06-06-2023) 

### ISSUE THREAD

**Issue by Priyanka-Chatterjee-2000** [turbot/steampipe-mod-kubernetes-compliance#44]
**Is your feature request related to a problem? Please describe.**

CIS [Reference](https://www.cisecurity.org/benchmark/kubernetes)
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rajlearner17** [comment]
CIS v0.7.1 is a minor release with no significant change to the controls except the below tag changes. Hence we are not releasing any minor version changes. 


CIS 5.1.3 | Minimize wildcard use in Roles and ClusterRoles (Manual) |   | Manual > Implemented | No Significant Change Except below doc + cis_level to include both level-1 and 2 Profile Applicability:• Level 1 - Master Node• Level 2 - Master Node
-- | -- | -- | -- | --
CIS 5.1.6 | Ensure that Service Account Tokens are only mounted where necessary (Manual) |   | Manual > Implemented | No Significant Change Except below doc + cis_level to include both level-1 and 2 Profile Applicability:• Level 1 - Master Node• Level 2 - Master Node
CIS 5.3.2 | Ensure that all Namespaces have Network Policies defined (Manual) |   | Manual > Implemented | NO CHANGE
CIS 5.7.2 | Ensure that the seccomp profile is set to docker/default in your pod definitions (Manual) |   | Manual > Implemented | NO CHANGE
CIS 5.7.4 | The default namespace should not be used (Manual) |   | Manual > Implemented | NO CHANGE
