### ISSUE TITLE
Add CIS Kubernetes Foundations Benchmark v1.8.0-(10-05-2023) 

### ISSUE THREAD

**Issue by Priyanka-Chatterjee-2000** [turbot/steampipe-mod-kubernetes-compliance#76]
**Is your feature request related to a problem? Please describe.**
CIS [Reference](https://www.cisecurity.org/benchmark/kubernetes)
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by khushboo9024** [comment]
Currently, this isn't needed as we have plans to add provider-specific CIS benchmarks and controls. (Example: CIS Google Kubernetes Engine (GKE) Benchmark)
