### ISSUE TITLE
Link to NSA/CISA technical security report (pdf) is broken.

### ISSUE THREAD

**Issue by chandru89new** [turbot/steampipe-mod-kubernetes-compliance#77]
**Describe the bug**
We seem to be linking to the NSA/CISA Technical Security Report (https://media.defense.gov/2021/Aug/03/2002820425/-1/-1/1/CTR_KUBERNETES%20HARDENING%20GUIDANCE.PDF) in a couple of places but this link is now broken.

**Steampipe version (`steampipe -v`)**
NA

**Plugin version (`steampipe plugin list`)**
NA

**To reproduce**
We link to the document on these pages:
- https://hub.steampipe.io/mods/turbot/kubernetes_compliance/dashboards/dashboard.nsa_cisa_v1
- https://hub.steampipe.io/mods/turbot/kubernetes_compliance

Correct link: https://media.defense.gov/2022/Aug/29/2003066362/-1/-1/0/CTR_KUBERNETES_HARDENING_GUIDANCE_1.2_20220829.PDF

**Comment by aniketh-varma** [comment]
Hi, is this issue still up for grabs?

**Comment by cbruno10** [comment]
Hey @aniketh-varma , yes it is! Any PRs for this fix would be greatly appreciated, thanks!

**Comment by aniketh-varma** [comment]
Hey @cbruno10, I have raised the [PR](https://github.com/turbot/steampipe-mod-kubernetes-compliance/pull/80) to solve this issue. Please review the same, Thanks!
